import { Account, Reservation } from "@/types";

export const accounts: Account[] = [
  { id: "free-cash", name: "Free cash", isDefault: true, colorClass: "bg-emerald-500" },
  { id: "drug-purchase", name: "Drug purchase", colorClass: "bg-sky-500" },
  { id: "treatment-fund", name: "Treatment fund", colorClass: "bg-rose-500" },
  { id: "stock-fund", name: "Stock fund", colorClass: "bg-amber-500" },
];

export const reservations: Reservation[] = [
  {
    id: "#RSV001",
    isNew: true,
    patientName: "Albert Flores",
    patientInitials: "AF",
    avatarColor: "bg-orange-200",
    numberOfBillsPaid: 0,
    numberOfBillsTotal: 2,
    reservationDate: "23/05/2022",
    totalAmount: 2311,
    paymentStatus: "partially_paid",
    bills: [
      {
        id: "#1240",
        billNo: "#BILL00120",
        label: "Booking Fee",
        amount: 311,
        status: "unpaid",
        billDate: "10/05/2022",
        billTo: { name: "Albert Flores", address: "Jl. Sudirman No. 22, Jakarta Selatan 12190" },
        lineItems: [{ id: "li1", label: "Booking Fee", total: 311 }],
        subtotal: 311,
        tax: 0,
        total: 311,
      },
      {
        id: "#1241",
        billNo: "#BILL00121",
        label: "3 Treatment(s)",
        amount: 2000,
        status: "unpaid",
        billDate: "23/05/2022",
        billTo: { name: "Albert Flores", address: "Jl. Sudirman No. 22, Jakarta Selatan 12190" },
        lineItems: [
          { id: "li2", label: "Treatment (3)", total: 1800 },
          { id: "li3", label: "Component used (2)", total: 150 },
          { id: "li4", label: "Medicine (1)", total: 50 },
        ],
        subtotal: 2000,
        tax: 0,
        total: 2000,
      },
    ],
  },
  {
    id: "#RSV002",
    patientName: "Esther Howard",
    patientInitials: "EH",
    avatarColor: "bg-sky-200",
    numberOfBillsPaid: 0,
    numberOfBillsTotal: 2,
    reservationDate: "23/05/2022",
    totalAmount: 535,
    paymentStatus: "partially_paid",
    bills: [
      {
        id: "#1244",
        billNo: "#BILL00123",
        label: "Booking Fee",
        amount: 20,
        status: "unpaid",
        billDate: "12/06/2022",
        billTo: { name: "Esther Howard", address: "Jl. Pulo Raya V No.14, Kebayoran Baru, Jakarta Selatan 12170" },
        lineItems: [{ id: "li5", label: "Booking Fee", total: 20 }],
        subtotal: 20,
        tax: 0,
        total: 20,
      },
      {
        id: "#1244",
        billNo: "#BILL00124",
        label: "2 Treatment(s)",
        amount: 435,
        status: "unpaid",
        billDate: "12/06/2022",
        billTo: { name: "Esther Howard", address: "Jl. Pulo Raya V No.14, Kebayoran Baru, Jakarta Selatan 12170" },
        lineItems: [
          { id: "li6", label: "Treatment (2)", total: 300 },
          { id: "li7", label: "Component used (1)", total: 120 },
          { id: "li8", label: "Medicine (1)", total: 15 },
        ],
        subtotal: 435,
        tax: 0,
        total: 435,
      },
    ],
  },
  {
    id: "#RSV003",
    patientName: "Kathryn Murphy",
    patientInitials: "KM",
    avatarColor: "bg-violet-200",
    numberOfBillsPaid: 2,
    numberOfBillsTotal: 2,
    reservationDate: "23/05/2022",
    totalAmount: 645,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1250",
        billNo: "#BILL00130",
        label: "2 Treatment(s)",
        amount: 645,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Kathryn Murphy", address: "Jl. Melati No. 9, Jakarta Barat 11530" },
        lineItems: [{ id: "li9", label: "Treatment (2)", total: 645 }],
        subtotal: 645,
        tax: 0,
        total: 645,
      },
    ],
  },
  {
    id: "#RSV004",
    patientName: "Brooklyn Simmons",
    patientInitials: "BS",
    avatarColor: "bg-rose-200",
    numberOfBillsPaid: 1,
    numberOfBillsTotal: 1,
    reservationDate: "23/05/2022",
    totalAmount: 667,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1251",
        billNo: "#BILL00131",
        label: "Treatment",
        amount: 667,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Brooklyn Simmons", address: "Jl. Kenanga No. 3, Jakarta Timur 13450" },
        lineItems: [{ id: "li10", label: "Treatment (1)", total: 667 }],
        subtotal: 667,
        tax: 0,
        total: 667,
      },
    ],
  },
  {
    id: "#RSV005",
    patientName: "Bessie Cooper",
    patientInitials: "BC",
    avatarColor: "bg-emerald-200",
    numberOfBillsPaid: 1,
    numberOfBillsTotal: 1,
    reservationDate: "23/05/2022",
    totalAmount: 343,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1252",
        billNo: "#BILL00132",
        label: "Treatment",
        amount: 343,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Bessie Cooper", address: "Jl. Anggrek No. 7, Jakarta Utara 14140" },
        lineItems: [{ id: "li11", label: "Treatment (1)", total: 343 }],
        subtotal: 343,
        tax: 0,
        total: 343,
      },
    ],
  },
  {
    id: "#RSV006",
    patientName: "Arlene McCoy",
    patientInitials: "AM",
    avatarColor: "bg-amber-200",
    numberOfBillsPaid: 1,
    numberOfBillsTotal: 1,
    reservationDate: "23/05/2022",
    totalAmount: 900,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1253",
        billNo: "#BILL00133",
        label: "Treatment",
        amount: 900,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Arlene McCoy", address: "Jl. Cempaka No. 18, Jakarta Pusat 10220" },
        lineItems: [{ id: "li12", label: "Treatment (1)", total: 900 }],
        subtotal: 900,
        tax: 0,
        total: 900,
      },
    ],
  },
  {
    id: "#RSV007",
    patientName: "Jane Cooper",
    patientInitials: "JC",
    avatarColor: "bg-fuchsia-200",
    numberOfBillsPaid: 1,
    numberOfBillsTotal: 1,
    reservationDate: "23/05/2022",
    totalAmount: 650,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1254",
        billNo: "#BILL00134",
        label: "Treatment",
        amount: 650,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Jane Cooper", address: "Jl. Mawar No. 5, Jakarta Selatan 12210" },
        lineItems: [{ id: "li13", label: "Treatment (1)", total: 650 }],
        subtotal: 650,
        tax: 0,
        total: 650,
      },
    ],
  },
  {
    id: "#RSV008",
    patientName: "Darrell Steward",
    patientInitials: "DS",
    avatarColor: "bg-blue-200",
    numberOfBillsPaid: 1,
    numberOfBillsTotal: 1,
    reservationDate: "23/05/2022",
    totalAmount: 1200,
    paymentStatus: "fully_paid",
    bills: [
      {
        id: "#1255",
        billNo: "#BILL00135",
        label: "Treatment",
        amount: 1200,
        status: "paid",
        billDate: "23/05/2022",
        billTo: { name: "Darrell Steward", address: "Jl. Kenari No. 11, Jakarta Barat 11440" },
        lineItems: [{ id: "li14", label: "Treatment (1)", total: 1200 }],
        subtotal: 1200,
        tax: 0,
        total: 1200,
      },
    ],
  },
];
